### ISSUE TITLE
Memory leaks on nethermind clients

### ISSUE THREAD

**Issue by tropicar** [NethermindEth/nethermind#3852] opened 2022-03-01 16:47 UTC
**Describe the bug**
I and many of our users have been suffering memory leaks in the machines where the nethermind client is installed. The majority of the cases are in the nevermind client for the xdai network because we have more users that use this client, I don't discard that this happens for the nethermind ethereum clients.

**To Reproduce**
Context
I am a developer from DAppNode project. We install this client using docker-compose. This is the code of these "packages" that is the way we run the client. https://github.com/dappnode/DAppNodePackage-nethermind-xdai 
Steps to reproduce the behaviour:
1. Download the repo 
2. build de docker-compose
3. docker-compose up

**Expected behaviour**
After a while, the machine takes so much resources of the RAM, we have seen even use 45gb ram memory until the client crash. The expected behaviour would be this were not possible, is there some configuration we can add or some solution for this issue?

**Comment by alexpeterson91** [comment] 2022-03-05 20:54
duplicate of https://github.com/NethermindEth/nethermind/issues/3743

**Closed** 2022-03-10 12:39 UTC

**Comment by fortsoftware** [comment] 2022-06-13 02:20
In my case I still experience a memory leak on 1.13.2 (on debian). It is a slow increase of memory over time but it is a leak.

**Comment by alexpeterson91** [comment] 2022-06-13 03:52
> In my case I still experience a memory leak on 1.13.2 on debian. It is a slow increase of memory over time but it is a leak.

You're 100% right not sure why this was closed I'll reopen it's been wreaking havoc on my 2 machines dedicated to testing nethermind with dappnode for months.
