### ISSUE TITLE
Problem syncing Energy Web Chain - "Unable to init the peer manager" error 

### ISSUE THREAD

**Issue by WendellCathcart** [NethermindEth/nethermind#1971] opened 2020-05-27 22:30 UTC
**OS**: Ubuntu 18.04.4
**Nethermind client**: 1.8-41
**Chain**: Energy Web Chain (PoA network - very similar to Volta)

**Problem**: I've successfully synced the Volta testnet but when I add a config and chainspec for Energy Web Chain (the mainnet to the Volta testnet), it throws an error on startup and fails to find peers. Both networks use AuRa Proof-of-Authority spec and I've edited the config file to use the correct GenesisHash and PivotHash.

**Chainspec**: https://github.com/energywebfoundation/ewf-chainspec/blob/master/EnergyWebChain.json

**energyweb.cfg**:
```
{
  "Init": {      
    "WebSocketsEnabled": false,
    "StoreReceipts" : true,
    "IsMining": false,
    "ChainSpecPath": "chainspec/energyweb.json",
    "GenesisHash": "0x0b6d3e680af2fc525392c720666cce58e3d8e6fe75ba4b48cb36bcc69039229b",
    "BaseDbPath": "nethermind_db/energyweb",
    "LogFileName": "energyweb.logs.txt"
  },
  "Network": {
    "DiscoveryPort": 30303,
    "P2PPort": 30303
  },
  "JsonRpc": {
    "Enabled": false,
    "Host": "127.0.0.1",
    "Port": 8545    
  },
  "Db": {
    "WriteBufferSize": 16000000,
    "WriteBufferNumber": 4,
    "BlockCacheSize": 128000000,
    "CacheIndexAndFilterBlocks": true,
    "BlockInfosDbCacheIndexAndFilterBlocks": false
  },
  "Sync": {
    "FastSync": true,
    "PivotNumber" : 4000000,
    "PivotHash" : "0x4be7f727e22b9482b0fe36714cb3bad5688a6bce41e2e93478a90f7d403eb7b4",
    "PivotTotalDifficulty" : "1361129467683753853853498430000000000000000000",
    "FastBlocks" : true,
    "UseGethLimitsInFastBlocks" : false,
    "FastSyncCatchUpHeightDelta": 10000000000
  },
  "EthStats": {
    "Enabled": false,
    "Server": "ws://localhost:3000/api",
    "Name": "Nethermind Energy Web",
    "Secret": "secret",
    "Contact": "hello@nethermind.io"
  },
  "Metrics": {
    "NodeName": "Energy_Web",
    "Enabled": false,
    "PushGatewayUrl": "http://localhost:9091/metrics",
    "IntervalSeconds": 5
  }
}
```

**Errors from line 8 onward**:

```
2020-05-27 15:56:01.7826|INFO|1|Grafana / Prometheus metrics are disabled in configuration 
2020-05-27 15:56:02.2883|INFO|1|Using http://ipv4.icanhazip.com to get external ip 
2020-05-27 15:56:03.5485|INFO|1|Block tree initialized, last processed is 0 (0x0b6d3e...39229b), best queued is 0, best known is 0, lowest inserted header , body  
2020-05-27 15:56:03.8337|INFO|1|No block tree levels to review for fixes. All fine. 
2020-05-27 15:56:03.8580|WARN|1|Using the local IP override: NetworkConfig.LocalIp = 10.0.2.15 
2020-05-27 15:56:03.8580|WARN|1|Using the external IP override: NetworkConfig.ExternalIp = 24.9.202.110 
2020-05-27 15:56:04.0563|INFO|6|Loaded 0 static nodes from file: /home/ad/nethermind/Data/static-nodes.json 
2020-05-27 15:56:04.2161|ERROR|5|Unable to init the peer manager. System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Nethermind.Stats.Model.Node.SetIPEndPoint(String host, Int32 port)
   at Nethermind.Network.PeerLoader.LoadConfigPeers(List`1 peers, IEnumerable`1 networkNodes, Action`1 nodeUpdate)
   at Nethermind.Network.PeerLoader.LoadConfigPeers(List`1 peers, String enodesString, Action`1 nodeUpdate)
   at Nethermind.Network.PeerLoader.LoadPeers(IEnumerable`1 staticNodes)
   at Nethermind.Network.PeerManager.LoadPersistedPeers()
   at Nethermind.Network.PeerManager.Init()
   at Nethermind.Runner.Ethereum.Steps.InitializeNetwork.InitPeer()
2020-05-27 15:56:04.5133|INFO|1|ReceiptsDb migration disabled. Finding logs when multiple blocks receipts need to be scanned might be slow. 
2020-05-27 15:56:04.5665|INFO|1|
======================== Nethermind initialization completed ========================
Version      : 1.8.41-0-8452b7da9-20200527/X64-Linux 5.3.0-28-generic/Core3.1.3
This node    : enode://63e87cab4871b767b26a24a139da80adbc7fc3535a581435cccfb0fa46b2602b6de34da708fb6ef413e4d336b4beb2c123509475fe945446169840e2eedc9d01@24.9.202.110:30303
Node address : 0x6b3681a2b2ae5c3c6d8d0a93a579dadddf5de803 (do not use as an account)
Mem est tx   :     78MB
Mem est trie :    240MB
Mem est peers:     50MB
Mem est netty:     33MB
Mem est DB   :    487MB
Mem est      :    888MB
Genesis hash : 0x0b6d3e680af2fc525392c720666cce58e3d8e6fe75ba4b48cb36bcc69039229b
External IP  : 
Ethereum     : 
Discovery    : 
DB location  : nethermind_db/energyweb
Chainspec    : chainspec/energyweb.json
Chain ID     : 246
Chain head   : 0 (0x0b6d3e...39229b)
===================================================================================== 
2020-05-27 15:56:04.5720|INFO|1|Json RPC is disabled 
2020-05-27 15:56:04.8546|INFO|6|Waiting for peers... 1s 
2020-05-27 15:56:04.8571|INFO|6|Sync peers - Initialized: 0 | All: 0 | Max: 50 
2020-05-27 15:56:05.8576|INFO|21|Waiting for peers... 2s
```

**Comment by tkstanczak** [comment] 2020-05-27 22:38
@LukaszRozmej would you check if the host names (not IP addresses) are allowed for bootnodes in chainspec.
This should be easy to fix since we already support it in other places.
Then would you be able to check quickly if you can sync this (and Volta).

![image](https://user-images.githubusercontent.com/498913/83079173-27f0d800-a073-11ea-98cd-d9295f844ace.png)

**Comment by tkstanczak** [comment] 2020-05-27 22:40
@WendellCathcart we will check that and will get back to you - this seems to be an issue with the bootnodes being required to be speced with IP addresses
we will aim at fixing it soon

**Comment by WendellCathcart** [comment] 2020-05-27 22:44
Great, thanks. I'll test replacing the bootnode URLs with IP addresses

**Comment by tkstanczak** [comment] 2020-05-27 22:46
If the pivot is not right for your chain it will not sync:
    "PivotNumber" : 4000000,
    "PivotHash" : "0x4be7f727e22b9482b0fe36714cb3bad5688a6bce41e2e93478a90f7d403eb7b4",
    "PivotTotalDifficulty" : "1361129467683753853853498430000000000000000000",

**Comment by tkstanczak** [comment] 2020-05-27 22:47
Is it a pivot from Volta? You can remove these three lines or update to some recent block on your chain

**Comment by WendellCathcart** [comment] 2020-05-27 22:48
I updated the config file to use the hash and difficulty for block 4,000,000 for Energy Web Chain so that should be alright unless I did it wrong :) http://explorer.energyweb.org/blocks/4000000/transactions

**Comment by tkstanczak** [comment] 2020-05-28 00:12
We will merge this tomorrow: Support DNS names in chainspec #1972
We have added pivot config for block 5900000.

It has to be total difficulty

**Comment by WendellCathcart** [comment] 2020-05-28 00:17
Awesome, thanks for your quick work on this!!

**Comment by tkstanczak** [comment] 2020-05-28 11:05
testing sync on our machines now

**Comment by tkstanczak** [comment] 2020-05-28 11:42
![image](https://user-images.githubusercontent.com/498913/83137238-bb142700-a0e0-11ea-890f-4d772bd917c8.png)
try with FastSync false maybe?

**Comment by tkstanczak** [comment] 2020-05-28 11:43
@WendellCathcart I will try to fully sync entire chain in archive mode and will let you know if all was good

**Comment by tkstanczak** [comment] 2020-05-28 13:17
![image](https://user-images.githubusercontent.com/498913/83146248-ed785100-a0ed-11ea-994b-d387b849ec98.png)
just running full archive on it in the background on my machine - looks good so far and I believe that the later blocks are more empty

**Comment by LukaszRozmej** [comment] 2020-05-28 18:24
There was a small issue with switching from fast sync to full sync. It is resolved in PR.

**Closed** 2020-05-29 09:45 UTC
Labels: AuRa, sync

**Comment by WendellCathcart** [comment] 2020-06-01 18:47
@tkstanczak thanks again for all of your help with this!
One small thing I noticed and one question:
First - I started syncing EWC with the latest release and it looks like energyweb.cfg specifies "energyWeb.json" as the chainspec which doesn't match what's in the chainspec folder ("energyweb.json"). Easy fix but wanted to flag that.

Also, I'm having mixed experience finding peers with both the volta and energyweb chains. For instance during the EWC sync it had 1 peer for about 10 minutes but now it's been "Waiting for peers..." + "Could not communicate with any nodes" for quite a while.

Did you encounter this and is there anything you'd recommend?

**Comment by tkstanczak** [comment] 2020-06-01 21:04
Yes, we have seen it with EWC when syncing from dynamic IPs and we were not sure what was going on. I think it was mainly in the fast sync as the archive synced nodes re running very well.

The node that I started 4 days ago has been running all the time since then and has 28 peers now:

![image](https://user-images.githubusercontent.com/498913/83454174-b5f20780-a453-11ea-8764-96a84331f1b6.png)

![image](https://user-images.githubusercontent.com/498913/83454312-e20d8880-a453-11ea-84fc-07575d02720e.png)

Are you running on a dynamic IP or behind a NAT?
Are you fully synced? maybe you can share the logs?

**Comment by tkstanczak** [comment] 2020-06-01 21:27
I think that the state sync with Parity nodes is a bit unstable - we have seen it also on POA Core sync. After it sync it is fine but the state sync drops peers often.

**Comment by tkstanczak** [comment] 2020-06-01 21:27
I will run energy web fast sync on the lastest version on a vm to try

**Comment by tkstanczak** [comment] 2020-06-01 21:31
I have justlaunched it from scratch and connected to our metrics on Grafana so will be able to verify how the sync progresses:
![image](https://user-images.githubusercontent.com/498913/83456391-8f35d000-a457-11ea-94a8-ae3bb27d446e.png)

**Comment by tkstanczak** [comment] 2020-06-01 21:42
![image](https://user-images.githubusercontent.com/498913/83457219-1c2d5900-a459-11ea-9f6e-f5d9c5e32f33.png)
so far very stable 15 peers but I want to see what happens when it switches to state sync (after bodies nd receipts are downloaded)

**Comment by WendellCathcart** [comment] 2020-06-01 22:21
Ah, thanks for the insight. I am behind a dynamic IP but syncing worked pretty consistently just last week with the same connection, so I'm not sure how to explain it. Here are the logs.

[energyweb.logs.txt](https://github.com/NethermindEth/nethermind/files/4713715/energyweb.logs.txt)

**Comment by tkstanczak** [comment] 2020-06-01 23:16
So I was able to sync today in under an hour on my local laptop and similarly on a VM.
I will review the logs tomorrow.

**Comment by tkstanczak** [comment] 2020-06-01 23:18
@WendellCathcart one important thing to add - the chain is very light so if we replace the config properly we can probably run the node with less than 500MB RAM

**Comment by tkstanczak** [comment] 2020-06-01 23:19
![image](https://user-images.githubusercontent.com/498913/83463673-a4662b00-a466-11ea-8107-3fcc8af80230.png)

**Comment by WendellCathcart** [comment] 2020-06-03 22:56
Hmm, I also got the EWC node to fully sync, but haven't had success syncing Volta. I set the Volta node on a DigitalOcean instance (static IP), used the latest release, and it still has trouble finding peers. I even tried disabling Fast Sync. Did you have trouble syncing Volta?

**Comment by LukaszRozmej** [comment] 2020-06-03 23:22
So I tried running my local node with some old peer db. I've got:

`2020-06-04 01:15:12.1943|Sync peers 6(6)/50
   [ B  ][H R ][Peer|eth63|6547825|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0|18.184.188.243:30303][140|0|0|0|0]
   [HB  ][    ][Peer|eth63|6547825|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0|3.121.165.10:30303][528|423|507|1969|0]
   [HB  ][    ][Peer|eth63|6547825|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0|52.31.129.130:30303][802|321|415|1670|0]
   [HBR ][    ][Peer|eth63|6547825|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0|52.60.210.190:30303][1326|297|297|1156|0]
   [HB  ][    ][Peer|eth63|6547825|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0|54.93.159.98:30303][545|474|554|2146|0]
   [HB  ][    ][Peer|eth63|6547825|Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0|99.81.92.124:30303][616|419|418|1790|0]
`

with those peers in db:

`[
  {
    "host": "118.25.221.220",
    "port": "30303",
    "address": "118.25.221.220:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://cfc21250bd5dbf9504434e1cdf4b947d278c9e92131de65c4d7be4f131b159529c07dd84dc0d992c7db78ce0ba0dc3671d9847f446179beccedc538af22c3fc3@118.25.221.220:30303"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "52.31.129.130",
    "port": "30303",
    "address": "52.31.129.130:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://bd228aa03cf4a88491c81c5f3ab4a1437df3b463081cc93943c4d3ab37f1e4f8081c6995eca076f717d4fdf9a277c750bd0289477ac151f1e2b024747dcd1747@52.31.129.130:30303"
  },
  {
    "host": "49.233.11.201",
    "port": "30333",
    "address": "49.233.11.201:30333",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://9f7fb100c9aaa5aaf728b38708a769ea3f89ea9dd0e95f04928dd535f3272d253a0455ad5b43e4f7d85cc44cebb2182dc2633863d11443b34f4d198b36a3d54b@49.233.11.201:30333"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "54.93.159.98",
    "port": "30303",
    "address": "54.93.159.98:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://8f8e35a6dcacfee946f46447b4703c84f4e485e478143997f86b1834e1b0bb78dab363d700dff3147442b9d3e2a1c521f79340c436eb7245a97c7fe385b89a5d@54.93.159.98:30303"
  },
  {
    "host": "13.124.197.115",
    "port": "30303",
    "address": "13.124.197.115:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://1659701915921f94194576090c3637ec35d7ccf1a6b206d16efffaf7b2e3f384d5ea2244838b5dda50287eb75bcfa8e9fbac31b383a736c6627ed9776b6a8dea@13.124.197.115:30303"
  },
  {
    "host": "34.228.155.198",
    "port": "30303",
    "address": "34.228.155.198:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://0786b4eb059f3350e7f1aaf1a0a928d8e144b58d69676dff5df87ce9ce0aaa78b6b4a9aea432fffa79e318f15d78d09819fb28d4fdce4c625778f72b317e6ffe@34.228.155.198:30303"
  },
  {
    "host": "200.16.28.28",
    "port": "30301",
    "address": "200.16.28.28:30301",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://82b66b13d7addcf9ffe1e4e972a105f6ccf50557161c4a0978a5d9ce595ababde609ea8a49897ae89b1d41e90551cb2e9241363238593e950ca68bd5af7c24d6@200.16.28.28:30301"
  },
  {
    "host": "110.10.124.152",
    "port": "21212",
    "address": "110.10.124.152:21212",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://1beab202f6709a2f4d233be28667348f7ebc5eb56df9b08336424d959a3ab0e11e26914be327b17785aaab8b075f067ff981e7425e2bf7f891361a3cfbbd7b91@110.10.124.152:21212"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "3.14.153.110",
    "port": "30303",
    "address": "3.14.153.110:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://da415e9ec8a0b055db75db47a1ede066022782b6c5e9385e30c72336e2750ecb9a49627445ff47dfe1bc3736616d1425c1e984d2672ff12c4c83c630f1d5834c@3.14.153.110:30303"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "18.184.188.243",
    "port": "30303",
    "address": "18.184.188.243:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://51a4ffc4e7b8c50a4e523c6d7f6f265b57dff44c70abdf3282c43ce5629298baf292bbd8bc80e40ef1ece8fa7dc7fd4a8642b8f248e0c7c92ab67b136d7b7050@18.184.188.243:30303"
  },
  {
    "host": "18.222.122.148",
    "port": "50502",
    "address": "18.222.122.148:50502",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://59731ad09b749d798c74272a7cb576b42ca595603fd6be76b15a52a9fb5a9d5213dd92f0ca2fc13c2bec49e4570c8210b8501cc9fbd5009585641fdb2afa05b5@18.222.122.148:50502"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "52.60.210.190",
    "port": "30303",
    "address": "52.60.210.190:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://9a7061c5a74fb555f1639db5dd4d012419c4355d64359ec478120fcbea2ddb798dba9c93cdf224de963a84e11f0538be69e76f9a017133c2dad831636874830c@52.60.210.190:30303"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "3.121.165.10",
    "port": "30303",
    "address": "3.121.165.10:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://5903b3acebdc4a34800f6923e5f3aec3ca7e5d1285bec4adb9f20ebb0f87a3bebdd748b1849ca1108a9f1e37ff9ced0b475292b8effc29e95d49ec438f244b02@3.121.165.10:30303"
  },
  {
    "host": "52.89.90.120",
    "port": "30303",
    "address": "52.89.90.120:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://9f612d6822bda29dd13134723cfd9a8bd3be363f4996276db80d6444de5c5ddd09a8e62aa68e33f1f0d2f31ff6f114489e8b6a0f6245a119f4798e802fd1197d@52.89.90.120:30303"
  },
  {
    "clientId": "Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0",
    "host": "99.81.92.124",
    "port": "30303",
    "address": "99.81.92.124:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://e487ebacbdad3418905d2ed7f009fa5dbd17d73880854884acc604c0afc1a60a396aa90cb2741278c555a4e30ffc6ffc1c29e83840aa22009ec92fe53f81ec04@99.81.92.124:30303"
  },
  {
    "host": "3.19.215.244",
    "port": "50505",
    "address": "3.19.215.244:50505",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://42c5a14bb5fe178e57bc344671bb4b665a4c88b854c83025fb9d4554d873f9283994509b7efa4aa19e834bb86a809e455ad06b89d1d8eb4f093cedd59a6d50a0@3.19.215.244:50505"
  },
  {
    "host": "54.37.194.57",
    "port": "30303",
    "address": "54.37.194.57:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://c851155ba1104a856c787b1e25feb4a96b2fdb1951f6b8cc6793434a2de6d8597b853d955a161a340608d919fed5025c300c5b38ce45cd7891be760e99f42535@54.37.194.57:30303"
  },
  {
    "clientId": "Geth/v1.8.27-stable/linux-amd64/go1.10.4",
    "host": "190.16.240.253",
    "port": "30303",
    "address": "190.16.240.253:30303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://e9c1172a4daf47b3ffd41503dfac80df1c7030e11c375e26141ae92caa2ec394daf20853b3006cd5a2d9032b7314b772d74a1a8c3cd6870f33d4beaac4b28cb5@190.16.240.253:30303"
  },
  {
    "host": "118.222.97.44",
    "port": "30403",
    "address": "118.222.97.44:30403",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://caf3296e31f6350b897b8a2072a29a470a86a5148e170ea37cb8b163cb922d0ec45af3c1b20bd0a0f5d36ac1127cdd02e6ff33a9367965b70858cbfd824ed477@118.222.97.44:30403"
  },
  {
    "host": "54.70.158.106",
    "port": "30303",
    "address": "54.70.158.106:30303",
    "isBootnode": true,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://59c9250cb805409e84c9cd0038e97d8e5e4605b928663675869ebdfd4c251d80ccad76267a5eb2f4362ddceb5ec671f7595463adfc0a12e9f68dbf233072db41@54.70.158.106:30303"
  },
  {
    "host": "149.56.240.153",
    "port": "32303",
    "address": "149.56.240.153:32303",
    "isBootnode": false,
    "isTrusted": false,
    "isStatic": false,
    "enode": "enode://405dadc7f659262ff708f93e7a962f7f6bff1f72ec2a2c714aa212a53876d07ab06a52ef359f2555e2983df5c451d7fb51512c772131bec396ea922fdbc25845@149.56.240.153:32303"
  }
]`

You can try with those nodes either putting enodes to static enodes file or just dropping attached
[peers.zip](https://github.com/NethermindEth/nethermind/files/4726647/peers.zip)

Trying from fresh DB I managed to connect to 4 peers almost instantaneously 
 peers part of DB.

**Comment by tkstanczak** [comment] 2020-06-03 23:55
I will try to sync Vilta tomorrow. For a long time we were not even testing
Volta as we thought you were not using it in Nethermind. We will add the
checks back.

**Comment by tkstanczak** [comment] 2020-06-04 15:36
Started on a VM - found two peers so far:
![image](https://user-images.githubusercontent.com/498913/83777620-89bbce00-a681-11ea-87df-212401013288.png)

**Comment by tkstanczak** [comment] 2020-06-04 17:15
@WendellCathcart  - the chainspec file was not updated after the latest Ethereum hard forks
also the Parity chainspec for the latest hard fork is not compatible with Nethermind (latest hard fork was the first one where we had to updated chainspec before Parity as ready and I do not think they cared about being compatible with us).

I have updated it on the master branch, I have also updated pivot.
Now we are syncing volta just fine.

**Comment by tkstanczak** [comment] 2020-06-04 17:15
![image](https://user-images.githubusercontent.com/498913/83789969-639d2a80-a68f-11ea-85d1-176dd724a21e.png)

**Comment by WendellCathcart** [comment] 2020-06-04 18:06
Beautiful, node started and restarted successfully, both times with 5+ peers. Thanks again for your help! 

Once it is synced, we want to try validating blocks with this node. As far as you know, should it be able to validate blocks (once it's added to the validator set)? 
Do I just need to set "IsMining" to true, or do anything else to enable validating?

**Comment by LukaszRozmej** [comment] 2020-06-05 00:34
You might need to add in config:
"Aura":
{
    "ForceSealing": true
}

**Comment by tkstanczak** [comment] 2020-06-05 10:18
Hi @WendellCathcart,
I am super glad that both Volta and Energy Web can fully sync and operate.
All the AuRa functionalities that have been delivered for POA (POSDAO, POA validation, various AuRa switches support) will work and be maintained indefinitely.
If there is anything specific for Volta or EnergyWeb that is not currently implemented it may be arranged as part of our premium support. Since we have confirmed everything has worked as planned for now we will be removing volta and energy web chainspecs from our official repo (as they impose some additional maintenance / test requirements) but everything should work just fine if you just use your own chainspec (with the minor differences between Parity and Nethermind as for the latest forks).
Our nodes have synced and been operating seamlessly for the last 24 hours on both chains. We will be switching them off on our VMs.

Every config file and chainspec in Nethermind needs to have the following items to be fully supported long-term:
 * automated and manually verified pivot updates for fast sync
 * updates reflecting config file changes
 * tests covering any config file format changes
 * updates to launcher file
 * smoke tests for chains on releases

We suggest setting up a fork of the repo where you could maintain the additional configs.

In case you would like to discuss support options we can provide all the above maintenance and also
 * 24/7 support with alerts for our team
 * monitored metrics via Grafana cloud
 * Seq logs searches and dashboard
 * performance monitoring and imporvements
 * extensions to JSON RPC and other parts of the system

We can also run nodes and validators for you and help with the setup of your nodes.
