### ISSUE TITLE
Remove Bouncy Castle entirely

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#388] opened 2019-02-11 06:37 UTC

**Comment by tkstanczak** [comment] 2019-02-11 06:39
I think it is responsible for 80/90% of memory allocations now

**Comment by tkstanczak** [comment] 2019-03-17 12:58
Agreements and KDF removed

**Comment by rubo** [comment] 2023-02-15 17:26
Duplicate of #5207

**Closed** 2023-02-15 19:37 UTC
Labels: duplicate, refactoring, performance
