### ISSUE TITLE
[GitHub Actions] Pipelines failed when triggered for new TAG

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4823] opened 2022-10-26 17:56 UTC
**Describe the bug**
Two Pipelines:
1. [RUN] Hive Tests
2. [RUN] CodeQL code analysis
Are failing when Tag is added to the branch - we need to check why is that happening and ensure all are green on tag trigger.

**Comment by rubo** [comment] 2023-01-08 12:40
Duplicate of #5098

**Closed by rubo** 2023-01-08 12:40 UTC
Labels: duplicate
