### ISSUE TITLE
Corruption after forced kill during state sync

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#3937] opened 2022-04-06 10:48 UTC
Nodes were syncing - state sync. 

2022-04-06 10:18:35.6480|Sync mode update failed RocksDbSharp.RocksDbException: Corruption: bad entry in block
   at RocksDbSharp.Native.rocksdb_get(IntPtr db, IntPtr read_options, Byte[] key, Int64 keyLength, ColumnFamilyHandle cf) in /src/rocksdb-sharp/RocksDbSharp/Native.Wrap.cs:line 109
   at Nethermind.Db.FullPruning.FullPruningDb.get_Item(Byte[] key) in /src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 71
   at Nethermind.Synchronization.ParallelSync.SyncProgressResolver.IsFullySynced(Keccak stateRoot) in /src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs:line 83
   at Nethermind.Synchronization.ParallelSync.SyncProgressResolver.SearchForFullState(BlockHeader startHeader) in /src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs:line 123
   at Nethermind.Synchronization.ParallelSync.SyncProgressResolver.FindBestFullState() in /src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs:line 96
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TakeSnapshot(UInt256& peerDifficulty, Int64 peerBlock) in /src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 557
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.Update() in /src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 188
   at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TimerOnElapsed(Object sender, ElapsedEventArgs e) in /src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 247
2022-04-06 10:18:36.6476|Waiting for peers... 11s
2022-04-06 10:18:36.6476|Sync mode update failed RocksDbSharp.RocksDbException: Corruption: bad entry in block
   at RocksDbSharp.Native.rocksdb_get(IntPtr db, IntPtr read_options, Byte[] key, Int64 keyLength, ColumnFamilyHandle cf) in /src/rocksdb-sharp/RocksDbSharp/Native.Wrap.cs:line 109
   at Nethermind.Db.FullPruning.FullPruningDb.get_Item(Byte[] key) in /src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 71

**Comment by LukaszRozmej** [comment] 2022-04-06 13:49
Duplicate of #3938

**Closed by LukaszRozmej** 2022-04-06 13:49 UTC
