### ISSUE TITLE
Issues with `eth_newFilter` and `eth_getFilterLogs`

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2319] opened 2020-09-17 00:31 UTC
I'm getting super random behavior from the following code:

https://gist.github.com/araa47/54d324e4fd3b9f19c766f4bf475b3607

Sometimes it returns `[]` and other times it returns a bunch of entries...

What is the expected behavior here?

Example:
```
>>> w3_archive = init_web3_archive()
Connected to web3 True
Current Block 10876373
>>> filt_archive = w3_archive.eth.filter({'fromBlock':10875523 , 'address': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' })
>>> filt_archive.get_all_entries()
[]
>>> 
>>> 
>>> 
>>> filt_archive.get_all_entries()
[{'address': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 'blockHash': HexBytes('0x67a48aae2b5ffe8ace017fbb170852562cf1f27f3a39d918acf5df76599e5832'), 'blockNumber': 10876374, 'data': '0x0000000000000000000000000000000000000000000000000000000059682f00', 'logIndex': 79, 'removed': False, 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x000000000000000000000000713bf16dca89ed7009005c633e162cff50f29c0e'), HexBytes('0x000000000000000000000000b4e16d0168e52d35cacd2c6185b44281ec28c9dc')], 'transactionHash': HexBytes('0x05a76e786583317705de1c2e6190a71a448c44827e55453326ad01fafcf2dff1'), 'transactionIndex': 1, 'transactionLogIndex': '0x0'}, {'address': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 'blockHash': HexBytes('0x67a48aae2b5ffe8ace017fbb170852562cf1f27f3a39d918acf5df76599e5832'), 'blockNumber': 10876374, 'data': '0x000000000000000000000000000000000000000000000000000000021d9f6540', 'logIndex': 2427, 'removed': False, 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x00000000000000000000000056178a0d5f301baf6cf3e1cd53d9863437345bf9'), HexBytes('0x0000000000000000000000001f8a6d8185b76f5ac08f335610a2390dab3225a8')], 'transactionHash': HexBytes('0x00c56b9898c01f84d35ba3fea247bd7462705396249748bfe454ae7f2ca5e410'), 'transactionIndex': 101, 'transactionLogIndex': '0x2'}, {'address': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 'blockHash': HexBytes('0x67a48aae2b5ffe8ace017fbb170852562cf1f27f3a39d918acf5df76599e5832'), 'blockNumber': 10876374, 'data': '0x000000000000000000000000000000000000000000000000000000021d9f6540', 'logIndex': 2429, 'removed': False, 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x0000000000000000000000001f8a6d8185b76f5ac08f335610a2390dab3225a8'), HexBytes('0x00000000000000000000000011111254369792b2ca5d084ab5eea397ca8fa48b')], 'transactionHash': HexBytes('0x00c56b9898c01f84d35ba3fea247bd7462705396249748bfe454ae7f2ca5e410'), 'transactionIndex': 101, 'transactionLogIndex': '0x4'}, {'address': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 'blockHash': HexBytes('0x67a48aae2b5ffe8ace017fbb170852562cf1f27f3a39d918acf5df76599e5832'), 'blockNumber': 10876374, 'data': '0x000000000000000000000000000000000000000000000000000000021d9f6540', 'logIndex': 2433, 'removed': False, 'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'), HexBytes('0x00000000000000000000000011111254369792b2ca5d084ab5eea397ca8fa48b'), HexBytes('0x0000000000000000000000003714f75770e331014df64961782e7db3fc78c1d0')], 'transactionHash': HexBytes('0x00c56b9898c01f84d35ba3fea247bd7462705396249748bfe454ae7f2ca5e410'), 'transactionIndex': 101, 'transactionLogIndex': '0x8'}]
```

If I call `filt_archive.get_all_entries()` again, I get a different set of data...

It kind of feels like the node is "building" the reply data behind the scenes and then just giving me whatever it currently has every time I call `filt_archive.get_all_entries()`

Does Infura perhaps cache this data and/or have it readily available so it doesn't error out / return [] / produce different results when it's called against Infura?

Tagging: @araa47

**Comment by LukaszRozmej** [comment] 2020-09-17 00:55
_getFilterChanges
Polling method for a filter, which returns an array of logs which occurred since last poll._

So after it gives you incremental changes since last pool, then updates when you pooled, so if you have 2nd call immediately before any new data comes in it will be empty.

**Comment by MysticRyuujin** [comment] 2020-09-17 02:51
luk:
> I think it works as expected
it gives you data only since last pool or filter creation

tkstanczak:
> I thonk it flushes all the logs since last vall
call
@luk , does it respect filter id?

Me:
> But, there's a "fromBlock" that's in the past...so how does that work?
Data after filter creation, for a block in the past?
I'm not disagreeing, just want to understand, Infura produces instant results, so I thought it's weird, idk
The explanation on GitHub would make since if the 2nd poll always contained data, but it doesn't. And neither does the 1st poll
I can call it like 5 times in a row and get zero data back
And again, the fromBlock is old
The only explanation that i can reason to is that getting the data is slower than expected and it's just returning what it has in the queue

**Comment by LukaszRozmej** [comment] 2020-09-22 10:42
hm... maybe on first batch we should return data from the past? Need to look into it.

**Comment by kwood** [comment] 2021-05-26 21:53
It seems that Nethermind ignores the fromBlock parameter?

Is there another way to query historical logs besides creating a filter?

**Comment by LukaszRozmej** [comment] 2021-05-28 23:48
@kwood best for that is eth_getLogs, @marcindsobczak can you check if there are any issues with our filters?

**Comment by Termina1** [comment] 2022-12-16 16:10
> It seems that Nethermind ignores the `fromBlock` parameter?
> 
> Is there another way to query historical logs besides creating a filter?

You can use eth_getFilterLogs to get all the data initially, for me it works fine.

**Comment by rubo** [comment] 2022-12-16 18:14
I believe this issue is a duplicate of #4687 which was fixed around two months ago.

**Closed by rubo** 2022-12-16 18:14 UTC
Labels: high priority
