### ISSUE TITLE
Invalid sync mode switch

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2803] opened 2021-02-18 08:32 UTC
2021-02-18 02:08:19.6888|INFO|101|Changing state Full, FastReceipts to WaitingForBlock, FastReceipts at processed:11859358|state:11877775|block:11877777|header:11877777|peer block:11877777

**Comment by dceleda** [comment] 2022-10-05 20:19
@kamilchodola have you observed that?
@tkstanczak do you remember if it was a random issue or caused by specific conditions/configuration?

**Comment by kamilchodola** [comment] 2023-01-09 10:43
@tkstanczak 
Not sure if I get this right, but I guess it will be more about processed block number in this logs from main thread, right?
I can see on one of my nodes having that:

Changing state Full, FastReceipts to WaitingForBlock, FastReceipts at processed:16365549|state:16365549|block:16365549|header:16365549|chain difficulty:58750003716598352816469|target block:16365548|peer block:16365548|peer total difficulty:58750003716598352816469

Regarding mode switch itself I think it is fine. It happens after:
`BeaconChain reorged during the sync or cache rebuilt`

I'm wondering if this may cause some missed attestations because during that moment Proc Queue increases so seems like we may have some timeout around this time, we need to catchup and may miss some blocks or process to late.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/43241881/211290132-cfc493dd-5980-41d7-a6ba-47a2a10a639a.png">


<img width="771" alt="image" src="https://user-images.githubusercontent.com/43241881/211290159-426f046d-4169-4f30-a1bd-ed02459ceb36.png">


@MarekM25 @asdacap

**Comment by kamilchodola** [comment] 2024-06-03 12:13
OK it seems like not actually our issue - at least not always :D

If during OldReceipts our processing will be too slow we may drop out of sync - it is likely to happen on very weak setups.

Also it is willing to happen when we lose connectivity with CL client so we obviously will be catching back up to the head.

Closing this for now as it is not a code issue rather depends highly on CL and hardwarre used.

**Closed by kamilchodola** 2024-06-03 12:13 UTC
Labels: bug
