### ISSUE TITLE
Batched eth_call request fails occasionally

### ISSUE THREAD

**Issue by sunce86** [NethermindEth/nethermind#6089] opened 2023-09-12 09:01 UTC
**Description**
Sometimes when I send batched eth_call request the response can't be decoded (not a valid json).

**Steps to Reproduce**
Send several eth_call requests in a batch (for example, `ERC20::balance_of()` calls):

```
[{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_call",
  "params": [
    {
      "to": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "data": "0x70a082310000000000000000000000000A59649758aa4d66E25f08Dd01271e891fe52199"
    },
    "latest"
  ]
},
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "eth_call",
  "params": [
    {
      "to": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "data": "0x70a08231000000000000000000000000cEe284F754E854890e311e3280b767F80797180d"
    },
    "latest"
  ]
}]
```

**Actual behavior**
Json response is missing the closing bracket and also missing the responses for other requests: 
`[{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000000","id":1}`

**Expected behavior**
Json response should be a valid json with closing bracket and containing all responses:
`[{"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000029d421433325b","id":1},{"jsonrpc":"2.0","result":"0x000000000000000000000000000000000000000000000000000272f2ab4b6e94","id":2}]`

**Screenshots**
/

**Desktop (please complete the following information):**
/

**Additional context**
Not necessarily these addresses from example above are used. I use different token addresses and also different owner addresses. Any idea what could be causing the premature return of invalid json?

**Logs**
```
Caused by:
   0: method 'balanceOf(address):(uint256)' failure: web3 error: Decoder error: Error("EOF while parsing a list", line: 1, column: 111), raw response: base, 754305318, [{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000000","id":754305253}
```

**Comment by emlautarom1** [comment] 2023-09-19 13:49
Hello, thanks for reporting this issue. Please provide the following information regarding your setup:
 - Operating System: [e.g. Windows]
 - Nethermind Version: [e.g. 1.17.0]
 - Installation Method: [e.g. GitHub Release/PPA/Homebrew/Docker]
 - Consensus Client: [e.g. Lodestar v1.4.3]
 
Currently, we cannot reproduce the issue on 24445a5cb3a51150542c114fdb49727aac200ec4. Is the Nethermind node you're using on a different network (maybe a public RPC)?

**Comment by emlautarom1** [comment] 2023-10-02 15:36
I'm going to be closing this issue since we could not reproduce it in our VMs using the latest Nethermind version. Please open a new ticket if you happen to face this issue again.

**Closed by emlautarom1** 2023-10-02 15:36 UTC
