### ISSUE TITLE
error when using proof_call with a from-address

### ISSUE THREAD

**Issue by simon-jentzsch** [NethermindEth/nethermind#1457] opened 2020-02-19 09:17 UTC
If I use `eth_call` with 
```js
{"to": "0x731a10897d267e19b34503ad902d0a29173ba4b1",
"data": "0x61bc221a", 
"from":"0x00a329c0648769a73afac7f9381e08fb43dbea72"
}
```

I get a correct response.

But using the same arguments with `proof_call` I get an internal VM-Error, which produces a `0x` -result without reporting this as error.

```js
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "result": "0x",
    "accounts": [],
    "blockHeaders": [
      "0xf90201a01e9eada6701d389c991dc8dc6db48e5cdac6b2fcc77240c9664184740ba0e7d4a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a09a49a6a8c0925d5f77b2e0649ddc6956c0191b2195baadd64a1345b07e70e55ea0405b3d00544fdc6afd541bda9c7981097bb8c8ada6476678ec77eb02f791447ca0d10582758a66c0e0a2c46ccbdb4242c38a6203dd0b120c21da2427be3c298672b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000002000000000000200000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001028405f5e10082a997845e4cfb568a4e65746865726d696e64a00000000000000000000000000000000000000000000000000000000000000000880000000000000000"
    ]
  }
}
```

If I run the same request without the `from` -property it works. The from-address also has enough balance.

To reproduce:

[reproduce.zip](https://github.com/NethermindEth/nethermind/files/4224122/reproduce.zip)

**Comment by tkstanczak** [comment] 2020-02-19 09:59
I will look into it later today. I will check with 1.6.4 and 1.6.5.

Was that a regression after you tested with the latest?

**Comment by simon-jentzsch** [comment] 2020-02-19 10:18
I don't think it was a bug introduced in 1.6.5., but after the bugfixes in 1.6.5 helped to pass more tests, it simply failed later, so I found this issue.

**Comment by tkstanczak** [comment] 2020-02-19 13:07
reproduced:
![image](https://user-images.githubusercontent.com/498913/74837156-22bc1880-5321-11ea-91eb-886cd3385b34.png)

**Comment by tkstanczak** [comment] 2020-02-19 14:06
The problem was caused by the nonce value being checked in proof calls

![image](https://user-images.githubusercontent.com/498913/74841710-64e95800-5329-11ea-9388-51b920023633.png)

**Closed** 2020-02-19 14:07 UTC
