### ISSUE TITLE
eth_getLogs is missing Transactions from the `toBlock`

### ISSUE THREAD

**Issue by simon-jentzsch** [NethermindEth/nethermind#1486] opened 2020-02-25 15:02 UTC
I'm using a local NethDev -chain to run tests.
After sending 2 Transactions, I ask for the current blocknumber and then run a eth_getLogs :

request:
```js
{"id":1,"
jsonrpc":"2.0",
"method":"eth_getLogs",
"params":[{
  "toBlock":"0x312",
  "address":"0xEb423ecD0306cbAE43805135710f4495c6Ff435e"
}] 
}
```

The result only contains the log from the first transaction:
```js
[[
  {
    "address": "0xeb423ecd0306cbae43805135710f4495c6ff435e",
    "blockHash": "0x2472f4bb13108d78f6507845eb3716c49d5bd82bfc2f329c967a2bc7227dc9bb",
    "blockNumber": "0x30f",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000046cb18dd2039fbe0f420b4ee06ab9b6009658c74000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000000022331000000000000000000000000000000000000000000000000000000000000",
    "logIndex": "0x3",
    "removed": false,
    "topics": [
      "0x0299d04a77b985319ad1c515644fefc6dce93659db62ce6dc2c184421d603f72"
    ],
    "transactionHash": "0x4fe2458fa2f48745e72f4daf0c2d6605ddf8eeb291daff85f04b3ac3e3a55ebe",
    "transactionIndex": "0x0",
    "transactionLogIndex": "0x3"
  }
]
```

If I look into the latest block ( which is the `fromBlock`-number ), I see the 2nd transaction and asking for the receipt gives me:

```js
{
  "transactionHash": "0x9396608b9f95a3ad7d8ccc2999b1fe069d432ed29608329f3c8b46b36505122f",
  "transactionIndex": "0x0",
  "blockHash": "0xce43059c866be04316e1c719bce3fc8f1c07311c6d946e6c221893610aaf1154",
  "blockNumber": "0x312",
  "cumulativeGasUsed": "0x386fc",
  "gasUsed": "0x386fc",
  "from": "0x3a37fa8a8f3c8efef147f251a052482976a243a2",
  "to": "0xeb423ecd0306cbae43805135710f4495c6ff435e",
  "contractAddress": null,
  "logs": [
    {
      "removed": false,
      "logIndex": "0x0",
      "transactionIndex": "0x0",
      "transactionHash": "0x9396608b9f95a3ad7d8ccc2999b1fe069d432ed29608329f3c8b46b36505122f",
      "blockHash": "0xce43059c866be04316e1c719bce3fc8f1c07311c6d946e6c221893610aaf1154",
      "blockNumber": "0x312",
      "address": "0xcc5f783d135765238608ad05d8748f6840b030ad",
      "data": "0x000000000000000000000000000000000000000000000000002386f26fc10000",
      "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        "0x0000000000000000000000003a37fa8a8f3c8efef147f251a052482976a243a2",
        "0x0000000000000000000000000f3ddbfb8f90a4595047673ef4190a68e8c2dc5d"
      ]
    },
    {
      "removed": false,
      "logIndex": "0x1",
      "transactionIndex": "0x0",
      "transactionHash": "0x9396608b9f95a3ad7d8ccc2999b1fe069d432ed29608329f3c8b46b36505122f",
      "blockHash": "0xce43059c866be04316e1c719bce3fc8f1c07311c6d946e6c221893610aaf1154",
      "blockNumber": "0x312",
      "address": "0xcc5f783d135765238608ad05d8748f6840b030ad",
      "data": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "topics": [
        "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
        "0x0000000000000000000000003a37fa8a8f3c8efef147f251a052482976a243a2",
        "0x000000000000000000000000eb423ecd0306cbae43805135710f4495c6ff435e"
      ]
    },
    {
      "removed": false,
      "logIndex": "0x2",
      "transactionIndex": "0x0",
      "transactionHash": "0x9396608b9f95a3ad7d8ccc2999b1fe069d432ed29608329f3c8b46b36505122f",
      "blockHash": "0xce43059c866be04316e1c719bce3fc8f1c07311c6d946e6c221893610aaf1154",
      "blockNumber": "0x312",
      "address": "0x0f3ddbfb8f90a4595047673ef4190a68e8c2dc5d",
      "data": "0x0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000ffff0000000000000000000000003a37fa8a8f3c8efef147f251a052482976a243a2000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000000022332000000000000000000000000000000000000000000000000000000000000",
      "topics": [
        "0x1ca262a77ac17942055c2ff991000041865fc4fe608b39c1f3c1073199656510"
      ]
    },
    {
      "removed": false,
      "logIndex": "0x3",
      "transactionIndex": "0x0",
      "transactionHash": "0x9396608b9f95a3ad7d8ccc2999b1fe069d432ed29608329f3c8b46b36505122f",
      "blockHash": "0xce43059c866be04316e1c719bce3fc8f1c07311c6d946e6c221893610aaf1154",
      "blockNumber": "0x312",
      "address": "0xeb423ecd0306cbae43805135710f4495c6ff435e",
      "data": "0x0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000ffff0000000000000000000000003a37fa8a8f3c8efef147f251a052482976a243a2000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000000022332000000000000000000000000000000000000000000000000000000000000",
      "topics": [
        "0x0299d04a77b985319ad1c515644fefc6dce93659db62ce6dc2c184421d603f72"
      ]
    }
  ],
  "logsBloom": "0x08000000008000000000000000000000000000000000000000000400000000000000000000000000000000000000000000200000000000000000000008200000000000000000000000000008000000000000000000000000000000000000000000000000000000000050000000000020000000800000000000000050000000000000000000000000000000000000000002000000000010000000000000000000020000000000000000000800000000000008000000000000000000000000020000000002000000000000000000000000000200000000000044000000040800000018000000000000000000000000000000000000000000200000000004100000",
  "status": "0x1",
  "error": ""
}
```

since the last log-entry clearly fulfills the filter as defined in the eth_getlogs, is should have been part of the result.

This test fails about 70% of the time, so somtimes it does get the right response.

**Comment by tkstanczak** [comment] 2020-02-26 09:31
assigning to @LukaszRozmej as this has been changed significantly in the recent version

**Comment by tkstanczak** [comment] 2020-02-27 23:01
hi @simon-jentzsch, on Tuesday we tried to reproduce this but we were receiving all correct responses
We are planning to prepare a 'no-reproduce' sample and in the meantime the only thing that we see as a potential problem is that you mentioned: 

{"id":1,"
jsonrpc":"2.0",
"method":"eth_getLogs",
"params":[{
  "toBlock":"0x312",
  "address":"0xEb423ecD0306cbAE43805135710f4495c6Ff435e"
}] 
}

In such cases 'fromBlock' is set by default to 'latest' which means that you will receive transactions at most from one block. We have confirmed that this was consistent with other clients.

**Comment by tkstanczak** [comment] 2020-02-27 23:08
Also, your request is for 'toBlock' 0x312' (so from latest to '0x312' and response coming shows '0x30f' so this seems a bit confusing. When you were pasting the examples did you mix different calls to better show the issue?

**Comment by LukaszRozmej** [comment] 2020-02-28 02:08
I just made the following test:

Setup:
```
nethermind> eth.blockNumber
Request complete in 2116848,0us
0.0
```
```
nethermind> eth.sendTransaction({"from": personal.listAccounts[0], "To":null, "Input":"600960005260206000a000", "Nonce":"0x0", "Value":"0x1"})
Request complete in 8973,3us
Request complete in 76150,7us
"0xbfa5e744ab71769a1e2153ba9544cd6ea76b870a4dcd0fe4b99adbcef6af9dbe"
```

```
nethermind> eth.sendTransaction({"from": personal.listAccounts[0], "To":null, "Input":"600960005260206000a000", "Nonce":"0x1", "Value":"0x1"})
Request complete in 1360,3us
Request complete in 6177,5us
"0xc03f923fdb25c0a42041db2566e6a0ec6d700b926966ac9367c9c00b869f42fb"
```

getLogs:

```
nethermind> eth.getLogs({})                                                                                                                   
Request complete in 5200484,1us
[
  {
    "address": "0x2946259e0334f33a064106302415ad3391bed384",
    "blockHash": "0xacdac10db9e9c23c6c814a4203dfde72512a40a09b7e5691e8de1a711adb229a",
    "blockNumber": "0x2",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000009",
    "logIndex": "0x0",
    "removed": false,
    "topics": [],
    "transactionHash": "0xc03f923fdb25c0a42041db2566e6a0ec6d700b926966ac9367c9c00b869f42fb",
    "transactionIndex": "0x0",
    "transactionLogIndex": "0x0"
  }
]
```

```
nethermind> eth.getLogs({"fromBlock":"0x1"})
Request complete in 8685049,9us
[
  {
    "address": "0xf2e246bb76df876cef8b38ae84130f4f55de395b",
    "blockHash": "0x84b74a334caa428b241e82fdc5392602a15f5f2f24b6cf9381c897289f7f6206",
    "blockNumber": "0x1",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000009",
    "logIndex": "0x0",
    "removed": false,
    "topics": [],
    "transactionHash": "0xbfa5e744ab71769a1e2153ba9544cd6ea76b870a4dcd0fe4b99adbcef6af9dbe",
    "transactionIndex": "0x0",
    "transactionLogIndex": "0x0"
  },
  {
    "address": "0x2946259e0334f33a064106302415ad3391bed384",
    "blockHash": "0xacdac10db9e9c23c6c814a4203dfde72512a40a09b7e5691e8de1a711adb229a",
    "blockNumber": "0x2",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000009",
    "logIndex": "0x0",
    "removed": false,
    "topics": [],
    "transactionHash": "0xc03f923fdb25c0a42041db2566e6a0ec6d700b926966ac9367c9c00b869f42fb",
    "transactionIndex": "0x0",
    "transactionLogIndex": "0x0"
  }
]
```

```
nethermind> eth.getLogs({"toBlock":"0x2"})
Request complete in 5152612,1us
[
  {
    "address": "0x2946259e0334f33a064106302415ad3391bed384",
    "blockHash": "0xacdac10db9e9c23c6c814a4203dfde72512a40a09b7e5691e8de1a711adb229a",
    "blockNumber": "0x2",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000009",
    "logIndex": "0x0",
    "removed": false,
    "topics": [],
    "transactionHash": "0xc03f923fdb25c0a42041db2566e6a0ec6d700b926966ac9367c9c00b869f42fb",
    "transactionIndex": "0x0",
    "transactionLogIndex": "0x0"
  }
]
```

So all looks fine to me. 

As lately there was quite large amount of changes in this field it would be good to know what version you are running? What version the DB was populated (probably the same as this is in memory db)? And can you check latest version (both release and pre-release one).

**Comment by simon-jentzsch** [comment] 2020-02-28 13:06
I used the latest release and it was still failing.
Here is a script to reproce it:

[reproduce.zip](https://github.com/NethermindEth/nethermind/files/4267159/reproduce.zip)

**Comment by LukaszRozmej** [comment] 2020-02-28 13:37
Thanks for great script! Investigating

**Comment by tkstanczak** [comment] 2020-02-29 12:23
![image](https://user-images.githubusercontent.com/498913/75607364-41bf6500-5aee-11ea-8d80-29776042f730.png)
which version are you using?

**Comment by tkstanczak** [comment] 2020-02-29 12:29
I am running this script on your chainspec and config (fresh in memory start, loaded via CLI)
[reproduce_logs.txt](https://github.com/NethermindEth/nethermind/files/4270268/reproduce_logs.txt)

It consistently returns two log events and the mentioned transaction.

**Comment by tkstanczak** [comment] 2020-02-29 12:34
@simon-jentzsch see above and let us try to guess if any of these are relevant:
* is your version one of the latests versions that include the recent logs blooms rewrite

if above is confirmed then
* is there maybe some issue with the disk access that blocks valid logs bloom update
* is there some timing issue - sleep 5 - is this sleep 5 seconds or 5 milliseconds?
(if 5 milliseconds then it may be not yet available if the previous sends are async)

**Comment by tkstanczak** [comment] 2020-02-29 14:00
@simon-jentzsch it seems that the problem is with NethDev that is not designed well to process multiple transactions in parallel well and not with the eth_getLogs itself.
If you execute these transactions more or less sequentially then it will all work fine already, I think.

we will fix it soon as part of the mining support work

**Comment by simon-jentzsch** [comment] 2020-03-02 06:06
hm.. as you can see in the reproduce.sh-script, I'm using the docker-image `nethermind/nethermind:1.6.17` 
and on my mac, I get the same output.

**Comment by tkstanczak** [comment] 2020-03-02 11:38
@simon-jentzsch yes, the problem exists but it is related to the Dev block producer not handling multiple transactions at once well enough
What I wnted to express before was that the logs / eth_getLogs operations are not at fault.

**Comment by LukaszRozmej** [comment] 2020-03-02 13:24
@simon-jentzsch @tkstanczak just FYI I got distracted by other urgent issue and then weekend came in when I was not available. I'm still looking into it.

1. NethDev is currently not consistent and can loose race-condition with json-rpc. I will try fixing that.
2. I'm looking into if there arn't some edge cases that break down for eth_getLogs again based on multithreaded race-conditions.

**Comment by LukaszRozmej** [comment] 2020-03-02 16:14
@simon-jentzsch I have found the issue, some of our internal buffers weren't flushed immediately when creating optimized bloom index for searches, this could cause that some latest blocks bloom changes weren't picked up on search. This also explains inconsistency in how it sometimes worked for us and other times didn't. I created a PR that fixes it.

**Comment by tkstanczak** [comment] 2020-03-02 17:57
ok, this explains why I was not able to reproduce it - I was using an 'in memory' database

**Closed** 2020-03-03 18:26 UTC
Labels: bug
