### ISSUE TITLE
PPA says it's up to date but nethermind is still an older version

### ISSUE THREAD

**Issue by xtc0r** [NethermindEth/nethermind#4357] opened 2022-08-03 17:18 UTC
Created a new issue as requested by @smartprogrammer93 in #4347 

**Describe the bug**

I installed Nethermind 1.13.4.0  via PPA. Two days later 1.13.5.0 came out and I performed
`apt update && apt upgrade`
I saw that 1.13.5.0 was downloaded.
But `nethermind --version` gives me `Nethermind/v1.13.4-0-3e5972c24-20220803/X64-Linux/6.0.6`. Also `cat /usr/share/nethermind/git-hash` gives me `1.13.4-0-g3e5972c24`.

But `sudo apt list nethermind` gives me `nethermind/focal,now 1.1350 amd64  [installed]`

Nethermind process was restarted several times and the system was rebooted as well. It didn't change anything.

**To Reproduce**
Run
`apt update && apt upgrade`

**Expected behavior**
Nethermind is updated to the latest version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-122-generic x86_64)

**Comment by LukaszRozmej** [comment] 2022-08-05 06:29
possible duplicate of #4347

**Comment by smartprogrammer93** [comment] 2022-08-05 06:39
@LukaszRozmej That is my mistake. Since that issue had the docs work, i asked the author to create a seperate issue thinking i can close that one. Then i realized that the issue is mainly about the version not the docs.

**Closed** 2022-08-05 06:39 UTC
Labels: devops, release
