### ISSUE TITLE
during start of goerli from console

### ISSUE THREAD

**Issue by roninkaizen** [NethermindEth/nethermind#931] opened 2019-10-25 00:53 UTC
2019-10-25 00:52:15.0804|Error during ethereum runner start|System.TypeInitializationException: The type initializer for 'Nethermind.Core.Extensions.Bytes' threw an exception.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Avx.LoadVector256(Byte* address)
   at Nethermind.Core.Extensions.Bytes..cctor() in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Core/Extensions/Bytes.cs:line 331
   --- End of inner exception stack trace ---
   at Nethermind.Core.Extensions.Bytes.ToHexString(Byte[] bytes, Boolean withZeroX, Boolean noLeadingZeros, Boolean withEip55Checksum) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Core/Extensions/Bytes.cs:line 600
   at Nethermind.Core.Address.ToString(Boolean withZeroX, Boolean withEip55Checksum) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Core/Address.cs:line 170
   at Nethermind.KeyStore.FileKeyStore.StoreKey(PrivateKey key, SecureString password) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.KeyStore/FileKeyStore.cs:line 226
   at Nethermind.Wallet.DevKeyStoreWallet..ctor(IKeyStore keyStore, ILogManager logManager) in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Wallet/DevKeyStoreWallet.cs:line 59
   at Nethermind.Runner.Runners.EthereumRunner.SetupKeyStore() in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs:line 257
   at Nethermind.Runner.Runners.EthereumRunner.Start() in /root/repo_pub/nethermind/src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs:line 213

**Comment by tkstanczak** [comment] 2019-10-25 08:42
This is caused by a missing check for AVX2 support in a new optimization which will fail on some prcoessors (mainly manufactured before 2013).

**Comment by tkstanczak** [comment] 2019-10-25 17:57
fixed in 1.1.4

**Closed by tkstanczak** 2019-10-25 17:57 UTC
Labels: bug
