### ISSUE TITLE
eth_estimateGas occasionally returns invalid gas limit and causing tx to run out of gas

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5706] opened 2023-05-17 11:16 UTC
**Description**
According to Discord user:
nflaig 
Hey, I've been using Nethermind as RPC with Metamask for a while now but I noticed on few occasions that the eth_estimateGas API returns incorrect gas limits causing txs to run out of gas (e.g. https://etherscan.io/tx/0x4ce8bf18b702ad810bded432b4f59b20ee038b6828fb45e633cc199c944c2fce).

I created a gist (https://gist.github.com/nflaig/ea5b1b3f0413cd36e4391cad110ec177) to reproduce this for the failed tx I reported above.

We should not throw out of gas for sure (we can have different estimation than others but we should estimate enough value of gas for sure)

**Comment by deffrian** [comment] 2023-05-18 07:16
Related to #5637?

**Comment by emlautarom1** [comment] 2023-07-11 15:02
On transaction https://etherscan.io/tx/0x4ce8bf18b702ad810bded432b4f59b20ee038b6828fb45e633cc199c944c2fce I see that the gas limit is 216,894 while the actual usage is 207,046. This looks OK to me, am I missing something?

**Comment by emlautarom1** [comment] 2023-07-11 15:13
Also, I could not reproduce the issue:

Running the following command using `Nethermind.Cli`:

```
eth.estimateGas({from: "0x9d055dd23de15114ec95921208c741873ede8558", to: "0xe74bc1c4c27284ab7dbcf55f71fcc04b832fc32c", data: "0x73053410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000342f697066732f516d61624763754354786a57637a6b766f323977616d69355057435372514435656e744c62717a7a55486b79566f000000000000000000000000"})
```

*Note: the JSON body is the same as in the gist*

I get the following outputs based on the node address:
- `https://rpc.gnosis.gateway.fm`: `"0x58e8"` (official Gnosis Chain RPCs)
- `http://localhost:8545/`: `"0x6518"` (local Nethermind)

Note that Nethermind produces a higher estimation, not lower.

All Nethermind tools (`CLI` and `Runner`) are using version 1.21.0-unstable (commit 43660b6a730730b9cd561f116cf546660fabe6da)

**Comment by emlautarom1** [comment] 2023-07-11 15:51
Using the JS script (with `ethers`), I get the same gas estimations. Probably the issue has already been fixed (I'll do some research to figure out when)

**Comment by emlautarom1** [comment] 2023-07-11 19:24
I went back all the way to v1.16.0 and I always get the same estimation (`"0x6518"`). I didn't go back any further since it requires downgrading to .NET SDK 6.

**Comment by nflaig** [comment] 2023-07-17 13:18
> I see that the gas limit is 216,894 while the actual usage is 207,046

The tx definitely failed due to out of gas, see https://dashboard.tenderly.co/tx/mainnet/0x4ce8bf18b702ad810bded432b4f59b20ee038b6828fb45e633cc199c944c2fce.

Regarding the example in my gist (https://gist.github.com/nflaig/ea5b1b3f0413cd36e4391cad110ec177), I updated the data for the tx. The previous data would produce a failed tx since the state of the contract changed.

Looks like there was an update https://github.com/NethermindEth/nethermind/pull/5800 which is part of v1.20.0. I am still on v1.19.3 which produces incorrect gas estimate but will re-test once my Nethermind client is updated to latest.

I also gave `https://rpc.gnosis.gateway.fm` a try, it seems to produce a sufficient gas limit, is this mainnet or gnosis? I can't imagine that this gnosis because the contract I am getting an estimate for doesn't even exist there

```
> node estimate-gas.js 
Nethermind v1.19.3: 216894
Nethermind (https://rpc.gnosis.gateway.fm): 22760
```

**Comment by emlautarom1** [comment] 2023-07-17 19:34
**Please, disregard my initial comments, I had the wrong assumption that this issue was related to Gnosis chain.**

---

I've tested the updated tx with the new data and I'm getting the following estimations using various RPCs:

- `Ankr-erigon/2.48.0/linux-amd64/go1.20.5` (https://rpc.ankr.com/eth) estimated `217470`
- `Alchemy-Geth/v1.11.5-stable-a38f4108/linux-amd64/go1.20.2` (https://eth-mainnet.g.alchemy.com/v2/demo) estimated `217470`
- `Llama-llamanodes_web3_proxy/v0.36.0` (https://eth.llamarpc.com) estimated `217470`
- `blxrbdn-Geth/v1.11.5-stable-01c4d602/linux-amd64/go1.20.2` (https://virginia.rpc.blxrbdn.com) estimated `217470`

Locally, I'm getting the following estimations:

- `Erigon/2.48.0-stable-084acc1a` estimated `25880`
- `Geth/v1.12.0-stable-e501b3b0/linux-amd64/go1.20.3` estimated `25880`
- `Nethermind/v1.21.0-unstable+a35f97da/linux-x64/dotnet7.0.7` estimated `25880`

Locally I'm getting completely wrong estimations, maybe because I don't have mainnet synced.

I've also run a new simulation and the estimation that you're getting `216894` indeed produces an out of gas error, while the estimation produced by various RPCs using Geth/Erigon produce an estimation of `217470` which make the transaction actually go through (see: https://dashboard.tenderly.co/emlautarom1/project/simulator/b61e0080-083f-44f9-a318-a670c277ac99).

**Comment by emlautarom1** [comment] 2023-07-17 19:49
Could you please detail how are you running Nethermind? Also, what CL are you using?

**Comment by nflaig** [comment] 2023-07-17 20:08
Running via eth-docker, see [nethermind.yml](https://github.com/eth-educators/eth-docker/blob/main/nethermind.yml). I just reduced the peer count to 25, besides that using defaults. Updated to v1.20.0 today to test if issue is fixed on that release.
CL is Lodestar v1.9.1, default config as well for the most part.
I haven't re-synced Nethermind in almost a year, I think DB was pruned twice during that time.

Do you guys have a public Nethermind RPC to use? I encountered multiple failed tx in the past due to insufficient gas limit, could just use another node and see if I face the issue there as well. Although the dappnode publish package txs are 100% of the time wrong estimated if I use my node would be curious if another node would produce different results.

**Comment by emlautarom1** [comment] 2023-07-18 13:50
> Do you guys have a public Nethermind RPC to use? 
At this time we don't have a public RPC. I've mentioned this to the team and it's going to be taken into consideration.

**Closed** 2023-08-03 15:07 UTC
Labels: rpc
